version: 2

jobs:
  Install Dependencies:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: "npm install"
      - save_cache:
          key: "node_modules-{{ .Branch }}-{{ .Revision }}"
          paths:
            - node_modules

  Lint:
    docker:
      - image: "circleci/node:14"
    steps:
      - checkout
      - restore_cache:
          keys:
          - "node_modules-{{ .Branch }}-{{ .Revision }}"
      - run: "mkdir -p reports"
      - run: "./node_modules/.bin/eslint webextension test --format=junit | tee reports/eslint.xml"
      - store_test_results:
          path: reports

  Mocha:
    docker:
      - image: "circleci/node:14"
    steps:
      - checkout
      - restore_cache:
          keys:
          - "node_modules-{{ .Branch }}-{{ .Revision }}"
      - run: "mkdir -p reports"
      - run: "./node_modules/.bin/mocha test --reporter=xunit | tee reports/mocha.xml"
      - store_test_results:
          path: reports

workflows:
  version: 2
  Install Dependencies, Lint, and Mocha:
    jobs:
      - Install Dependencies
      - Lint:
          requires:
            - Install Dependencies
      - Mocha:
          requires:
            - Install Dependencies
