version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:8
    steps:
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires: build
